### PR TITLE
Wrap QingStor API as file object

### PR DESCRIPTION
**Pull request by wangzw**

### CODE REVIEW

**Comment by wangzw** [comment]
The use case:

We want to backup our database to QingStor.  
Backup file is usually very large, from many GB to 1TB for one file. 
And there are also some small control files, only many KB.

Our backup scripts was written by Python and currently backup database to filesystem. So if we can write data into QingStor as "File", it would be very easy to implement.

**Comment by ksellesk** [comment]
@wangzw Do you mean that you need to directly write string to qingstor object? We plan to provide "key.set_contents_from_string" method, it may cover you case.

**Comment by wangzw** [comment]
Not yet.

In our case, the content which we want to write into QingStor is dynamically generated and huge. It is impossible to buffer the content into a string or into a file on disk. 

We also need a file like interface to work with our legacy code.

**Comment by ksellesk** [comment]
So you need dynamically append(or tail) your backup files to Qingsor object?

**Comment by wangzw** [comment]
We do not need append. Once the object was created, we will never write to it again. 

Expected interface looks like:

```

object = create_a_new_object()

buffer = get_buffer_from_somewhere()
while buffer is not None:
    object.write(buffer)
    buffer = get_buffer_from_somewhere()

object.close()

```

It is a typical file like interface.  


Current API expose some internal concepts (part, multipart) which users really do not care about.  That's why I wrap the current API into file like API.

**Comment by osier** [comment]
Hi, @wangzw 

Thanks for the patches.

We already merged the first patch. But for the second one, basically it's based on qingcloud-sdk-python, and in principle, qingcloud-sdk-python should only provide the wrappers of  the http apis, so it won't be
merged. You can create a standalone project for it instead.

Regards,
Osier

**Pull request closed without merging**
